---
title: "chp-clustering"
author: "Ar"
date: '2022-06-07'
output: pdf_document
---

```{r}
library("flowCore")
library("flowViz")
fcsB = read.FCS("../data/Bendall_2011.fcs", truncate_max_range=FALSE)
slotNames(fcsB)   
```


```{r}
dim(Biobase::exprs(fcsB))
```





```{r}
markersB = readr::read_csv("../data/Bendall_2011_markers.csv")
mt = match(markersB$isotope, colnames(fcsB))
stopifnot(!any(is.na(mt)))
colnames(fcsB)[mt] = markersB$marker

```
```{r}
markersB$marker
```




```{r}
markersB
```



```{r}
match(c(1,2),c(1,1,1,2,2,2,1,1,1,2,2))
```

```{r}
?flowPlot
```


```{r}
colnames(fcsB)[4]
```


```{r}
flowPlot(fcsB, plotParameters=colnames(fcsB)[4:7], logy=TRUE)
```

```{r}
v1 = seq(0, 1, length.out = 100)
plot(v1, asinh(v1), type = 'l')
```


```{r}

v3 = seq(30, 3000, length = 100)
plot(v3, asinh(v3))
```


```{r}
asinhtrsf = arcsinhTransform(a=0.1, b=1)
fcsBT = transform(fcsB, 
                  transformList(colnames(fcsB)[-c(1,2,41)], asinhtrsf))
```

```{r}
colnames(fcsB)
```


```{r}
densityplot(~`CD4`, fcsB)
densityplot(~`CD4`, fcsBT)
```


```{r}
?kmeansFilter
```

```{r}
?filter
```



```{r}
kf = flowCore::kmeansFilter("CD3all"=c("Pop1", "Pop2"), filterId = "myKmFilter")
fres = flowCore::filter(fcsBT, kf)

summary(fres)
```

```{r}

fcsBT1 = flowCore::split(fcsBT, fres, population = "Pop1")
fcsBT2 = flowCore::split(fcsBT, fres, population = "Pop2")

```

```{r}
?flowPeaks
```


```{r}
library("flowPeaks")
fp = flowPeaks(Biobase::exprs(fcsBT)[, c("CD3all", "CD56")])
plot(fp)
```

```{r}
library("ggcyto")
library("labeling")
ggcd4cd8 = ggcyto(fcsB, aes(x=CD4, y=CD8))
ggcd4 = ggcyto(fcsB, aes(x=CD4))
ggcd8 = ggcyto(fcsB, aes(x=CD8))
p1 = ggcd4 + geom_histogram(bins=60)
p1b = ggcd8 + geom_histogram(bins=60)
asinhT = arcsinhTransform(a=0, b=1)
trans1 = transformList(colnames(fcsB)[-c(1,2,41)], asinhT)
fcsBT = transform(fcsB, trans1)
p1t = ggcyto(fcsBT, aes(x=CD4))+geom_histogram(bins=90)
p2t = ggcyto(fcsBT, aes(x=CD4, y=CD8))+geom_density2d(colour="black")
p3t = ggcyto(fcsBT, aes(x=CD45RA, y=CD20))+geom_density2d(colour="black")

```

```{r}
p1t
```
```{r}
p2t
```
```{r}
p3t
```

```{r}
?dbscan
```



```{r}
library("dbscan")

mc5 = Biobase::exprs(fcsBT)[,c(15,16,19,33, 40)]
res5 = dbscan::dbscan(mc5, eps=0.95, minPts=100)
mc5df = data.frame(mc5, cluster=as.factor(res5$cluster))
table(mc5df$cluster)
```

```{r}
ggplot(mc5df, aes(x=CD4, y=CD8, col=cluster))+geom_density2d()
ggplot(mc5df, aes(x=CD3all,  y=CD20, col=cluster))+geom_density2d()
```


```{r}

load("../data/Morder.RData")
```

```{r}
dim(Morder)
```
```{r}
length(Morder[2,])
```
```{r}
sqrt(sum((Morder[1, ] - Morder[2, ])^2))
```

```{r}
as.matrix(dist(Morder))[2,1]
```

```{r}
mut = read.csv("../data/HIVmutations.csv")
mut[1:3, 10:16]
```

```{r}
library("vegan")
```

```{r}
```


```{r}
as.matrix(vegdist(mut[,10:16]))[1:3,1:3]
```




```{r}
D = dist(t(Morder))
gene_clust = hclust(d = D)
plot(gene_clust, cex=0.25)
```

```{r}
gene_clust = hclust(d = D, method="ward.D2")
plot(gene_clust, cex=0.25)
```
```{r}
#BiocManager::install("pheatmap")
```

```{r}
library("pheatmap")
pheatmap(Morder, fontsize_col = 5, fontsize_row = 9)
```
```{r}
?pheatmap
```

```{r}
pheatmap(Morder, fontsize_col = 5, fontsize_row = 9, clustering_method="ward.D2")
```




```{r}
library('tidyverse')
```


```{r}
cc_data=read.csv("../SCR3_new_data_SP.csv",fileEncoding="UTF-8-BOM")
d = cc_data
```








```{r}
library("flowCore")
library("flowViz")
fcsB = read.FCS("../data/Bendall_2011.fcs", truncate_max_range=FALSE)
slotNames(fcsB)
```


```{r}
dim(Biobase::exprs(fcsB))
```





```{r}
markersB = readr::read_csv("../data/Bendall_2011_markers.csv")
mt = match(markersB$isotope, colnames(fcsB))
stopifnot(!any(is.na(mt)))
colnames(fcsB)[mt] = markersB$marker
```

```

```


```{r}
markersB
```



```{r}
match(c(1,2),c(1,1,1,2,2,2,1,1,1,2,2))
```

```{r}
?flowPlot
```


```{r}
flowPlot(fcsB, plotParameters=colnames(fcsB)[2:3], logy=TRUE)
```

```{r}
v1 = seq(0, 1, length.out = 100)
plot(log(v1), asinh(v1), type = 'l')
plot(v1, asinh(v1))
v3 = seq(30, 3000, length = 100)
plot(v3, asinh(v3))
```


```{r}
asinhtrsf = arcsinhTransform(a=0.1, b=1)
fcsBT = transform(fcsB, 
                  transformList(colnames(fcsB)[-c(1,2,41)], asinhtrsf))
```

```{r}
colnames(fcsB)
```


```{r}
densityplot(~`CD3all`, fcsB)
densityplot(~`CD3all`, fcsBT)
```


```{r}
?kmeansFilter
```



```{r}
kf = kmeansFilter("CD3all"=c("Pop1", "Pop2"), filterId = "myKmFilter")
fres = flowCore::filter(fcsBT, kf)
summary(fres)
```

```{r}

fcsBT1 = flowCore::split(fcsBT, fres, population = "Pop1")
fcsBT2 = flowCore::split(fcsBT, fres, population = "Pop2")

```



```{r}
library("flowPeaks")
fp = flowPeaks(Biobase::exprs(fcsBT)[, c("CD3all", "CD56")])
plot(fp)
```

```{r}
library("ggcyto")
library("labeling")
ggcd4cd8 = ggcyto(fcsB, aes(x=CD4, y=CD8))
ggcd4 = ggcyto(fcsB, aes(x=CD4))
ggcd8 = ggcyto(fcsB, aes(x=CD8))
p1 = ggcd4 + geom_histogram(bins=60)
p1b = ggcd8 + geom_histogram(bins=60)
asinhT = arcsinhTransform(a=0, b=1)
trans1 = transformList(colnames(fcsB)[-c(1,2,41)], asinhT)
fcsBT = transform(fcsB, trans1)
p1t = ggcyto(fcsBT, aes(x=CD4))+geom_histogram(bins=90)
p2t = ggcyto(fcsBT, aes(x=CD4, y=CD8))+geom_density2d(colour="black")
p3t = ggcyto(fcsBT, aes(x=CD45RA, y=CD20))+geom_density2d(colour="black")

```

```{r}
p1t
```
```{r}
p2t
```
```{r}
p3t
```


```{r}
library("dbscan")
mc5 = Biobase::exprs(fcsBT)[,c(11,15,16,19,25, 33, 40)]
res5 = dbscan::dbscan(mc5, eps=0.95, minPts=20)
mc5df = data.frame(mc5, cluster=as.factor(res5$cluster))
table(mc5df$cluster)
```

```{r}
ggplot(mc5df, aes(x=CD4, y=CD8, col=cluster))+geom_density2d()
ggplot(mc5df, aes(x=CD3all,  y=CD20, col=cluster))+geom_density2d()
```


```{r}
BiocManager::install("Morder")
```
```{r}
library("MOrder")
```

```{r}

load("../data/Morder.RData")
```

```{r}
dim(Morder)
```
```{r}
length(Morder[2,])
```
```{r}
sqrt(sum((Morder[1, ] - Morder[2, ])^2))
```

```{r}
as.matrix(dist(Morder))[2,1]
```

```{r}
mut = read.csv("../data/HIVmutations.csv")
mut[1:3, 10:16]
```

```{r}
library("vegan")
```

```{r}
```


```{r}
as.matrix(vegdist(mut[,10:16]))[1:3,1:3]
```




```{r}
D = dist(t(Morder))
gene_clust = hclust(d = D)
plot(gene_clust, cex=0.25)
```

```{r}
gene_clust = hclust(d = D, method="ward.D2")
plot(gene_clust, cex=0.25)
```
```{r}
#BiocManager::install("pheatmap")
```

```{r}
library("pheatmap")
pheatmap(Morder, fontsize_col = 5, fontsize_row = 9)
```
```{r}
?pheatmap
```

```{r}
pheatmap(Morder, fontsize_col = 5, fontsize_row = 9, clustering_method="ward.D2")
```




```{r}
library('tidyverse')
```


```{r}
cc_data=read.csv("../SCR3_new_data_SP.csv",fileEncoding="UTF-8-BOM")
d = cc_data
d1= filter(d,f2=="Medio_lateral")
d1$type=rep("MU",length(d1$x))
d1$type[d1$f1 %in% "WT"] = "WT"
e <- ggplot(data = d1, aes(x = f1, y = x,color=type))+
  stat_boxplot(geom ='errorbar',position = position_dodge(0.85), width=0.5)
```


```{r}
mx = c(0,0,0,1,1,1)
my = c(1,0,1,1,0,1)
mz = c(1,1,1,0,1,1)

mat = rbind(mx, my, mz)
dist(mat)
```
```{r}
```



d1= filter(d,f2=="Medio_lateral")
d1$type=rep("MU",length(d1$x))
d1$type[d1$f1 %in% "WT"] = "WT"
e <- ggplot(data = d1, aes(x = f1, y = x,color=type))+
  stat_boxplot(geom ='errorbar',position = position_dodge(0.85), width=0.5)
```


```{r}
mx = c(0,0,0,1,1,1)
my = c(1,0,1,1,0,1)
mz = c(1,1,1,0,1,1)

mat = rbind(mx, my, mz)
dist(mat)
```


